title: Further Wiki
email: hello@gofurther.digital
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wiki.gofurther.digital" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

include: [_pages]
